### ISSUE TITLE
Bad rendering of crossovers on same helix

### ISSUE THREAD

**Issue by tcosmo** [UC-Davis-molecular-computing/scadnano#198] opened 2020-02-14 10:29 UTC
When a crossover is done on the same helix, for instance like in the file `scadnano-python-package/test_outputs/cadnano_v2_import/test_huge_hex.dna` 
 it does not render well. It should do an arc so we can see it like in cadnano.

See attached screenshots from cadnano vs scadnano for that problem.
![Screenshot from 2020-02-14 10-26-26](https://user-images.githubusercontent.com/7616128/74523347-cf0e9100-4f14-11ea-828d-75d5532c05bc.png)
![Screenshot from 2020-02-14 10-26-10](https://user-images.githubusercontent.com/7616128/74523348-cfa72780-4f14-11ea-930e-990ff3a7a1fd.png)

**Comment by dave-doty** [comment] 2020-02-14 17:04
I assume that in the screenshots, the other endpoint of each crossover is far to the right, off the screen?

Is there a smaller example that can show the expected behavior, where the crossovers are not so long-range?

**Comment by dave-doty** [comment] 2020-07-02 01:25
Duplicate of #233 (technically this came first, but I want to keep the comment in the other issue about more generally using the orthogonal vector for the bowing direction).

**Closed by dave-doty** 2020-07-02 01:25 UTC
Labels: enhancement
