### ISSUE TITLE
Modify local scadnano files directly (no download) using the File System Access API

### ISSUE THREAD

**Issue by tcosmo** [UC-Davis-molecular-computing/scadnano#760] opened 2022-03-29 08:58 UTC
This is a feature that I discovered with an online SVG editor: https://boxy-svg.com/ 
(unfortunately, you need to register to test the feature)

Using Chrome it will directly modify your local SVG file on disk without the need to download each time:

![Screenshot from 2022-03-29 09-52-45](https://user-images.githubusercontent.com/7616128/160573910-632c96fb-052e-419a-8a73-b61163da9bae.png)

Asking you to authorise the website to modify your file directly on disk, if you say "yes" any further edit will directly be made to the file without the need to download each time.

I believe that this make use of the relatively new "File System Access API" https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API

A drawback is that is mainly only 
![Screenshot from 2022-03-29 09-58-45](https://user-images.githubusercontent.com/7616128/160574570-9d04cc77-80b3-441a-8752-e3e91648b8d2.png)
available on Chrome:

**Comment by dave-doty** [comment] 2022-03-29 09:27
Closing as duplicate of #619.

**Closed by dave-doty** 2022-03-29 09:27 UTC
Labels: enhancement
