### ISSUE TITLE
selections turn invisible rather than pink

### ISSUE THREAD

**Issue by Sam-Davidson** [UC-Davis-molecular-computing/scadnano#948] opened 2023-10-04 23:40 UTC
Currently in the web interface, any selection I make will turn the selected domain (or whatever) invisible rather than pink. I found this is true in Brave and Edge browsers.

**Comment by dave-doty** [comment] 2023-10-05 13:05
This might be a duplicate of this issue:

https://github.com/UC-Davis-molecular-computing/scadnano/issues/904

If you think it's different, can you show screenshots from an example and also upload the design here so I can try it myself?

**Comment by Sam-Davidson** [comment] 2023-10-05 20:19
The issue may be related. The problem for me happens during selections, not mouseovers. This zip file contains screenshots of the issue as well as the .sc file where I experience the problem.
[selection issue.zip](https://github.com/UC-Davis-molecular-computing/scadnano/files/12822953/selection.issue.zip)

**Comment by dave-doty** [comment] 2023-10-05 22:27
I think it is the same issue. I noticed when loading that the design is centered far from the origin. (Helix 0 is at x,y position 39,58). So since that bug seems to afflict strands far from the origin, I think it's affecting every strand in your design.

But it should be fixed soon.

**Comment by Sam-Davidson** [comment] 2023-10-06 01:13
Thanks!

**Comment by dave-doty** [comment] 2023-10-06 03:00
Closing as duplicate of #904.

**Closed by dave-doty** 2023-10-06 03:00 UTC

**Comment by dave-doty** [comment] 2023-10-06 03:02
This is fixed in the dev branch, should be working at https://scadnano.org/dev in about 20 minutes.
